apiVersion: apps/v1
kind: Deployment 
metadata:
 name: sa-web-app
spec:
 replicas: 1 
 minReadySeconds: 15
 selector:
  matchLabels:
   app: sa-web-app
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 1 
   maxSurge: 1
 template:
  metadata:
   labels:
    app: sa-web-app
  spec:
   containers:
    - image: tengfeiwang1031/sentiment-analysis-web-app
      imagePullPolicy: Always 
      name: sa-web-app
      env:
       - name: SA_LOGIC_API_URL
         value: "http://sa-logic-lb"
      ports:
       - containerPort: 8080
