apiVersion: v1
kind: Pod 
metadata:
 name: sa-logic
 labels:
  app: sa-logic
spec:
 containers:
  - image: tengfeiwang1031/sentiment-analysis-logic
    name: sa-logic
    ports:
    - containerPort: 5000 