apiVersion: v1
kind: Pod 
metadata:
 name: sa-web-app
 labels:
  app: sa-web-app
spec:
 containers:
  - image: tengfeiwang1031/sentiment-analysis-web-app
    name: sa-web-app
    ports:
    - containerPort: 8080 